= Using the OneCX Generator
To run the generator, you have to execute the following command:
[subs=+macros]
----
nx run nx-plugin-e2e:e2e
----

Furthermore, you will have to handle the following issues marked as "ACTION" in the generated files:

== Actions for search:

=== ACTION: Add translation

IN PROGRESS

=== ACTION: Add additional properties here

*Where this snippet can be found*: <feature>-bff.yaml. :

----
<Feature>Request:
      type: object
      properties:
        limit:
          type: integer
          maximum: 2500
        id:
          type: integer
          format: int64
        # ACTION: add additional properties here
----
Here you can add additional properties which you need for your <FeatureRequest>, e.g. status, creationDate ...

*HINT*: Please remove the "ACTION" comment after solving this issue



=== ACTION: Add the missing searchColumns

Exemplatory implementation of the searchColumns 

*Where this snippet can be found*: <feature>-search.component.ts. :
[subs=+macros]
----
export const <%= featurePropertyName %>SearchColumns = [
      {
      columnType: ColumnType.STANDARD,
      id: 'id',
      nameKey: 'TRANSLATION_STRING',
      filterable: true,
      sortable: true,
      predefinedGroupKeys: [
        'FEATURE_SEARCH.PREDEFINED_GROUP.DEFAULT',
        'FEATURE_SEARCH.PREDEFINED_GROUP.EXTENDED',
        'FEATURE_SEARCH.PREDEFINED_GROUP.FULL',
      ],
    },
]
----
Explanation of the properties:

*	columnType defines the type of the column. The following column types are available:
[subs=+macros]
----
export const enum ColumnType {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  DATE = 'DATE',
  RELATIVE_DATE = 'RELATIVE_DATE',
  TRANSLATION_KEY = 'TRANSLATION_KEY',
}
----
* The property 'id' provides the property of the column
* The property 'nameKey' provides the translation string. Furthermore, the translation needs to be added to the de.json and en.json file.
* The property 'filterable' indicates if the column is filterable
* The property 'sortable' indicates if the column is sortable
* The property 'predefinedGroupKeys' defines in which group sets the following column is available. Furthermore, the predefinedGroups can be selected in a dropdown on top of the search results table. If you want that your searchColumn only belongs to your default column group, then only add  'FEATURE_SEARCH.PREDEFINED_GROUP.DEFAULT'
// TODO: add the picture here if possible

=== ACTION: Please specify here your desired input fields
*Where this snippet can be found*: <feature>-search.component.html. :
[subs=+macros]
----
 <form [formGroup]="criteriaGroup">
      <div class="grid mt-0 p-fluid">
        <div class="col-12 md:col-3">
          <span class="p-float-label">
            <input
              id="name-input"
              pInputText
              type="text"
              formControlName="name"
              class="p-inputtext p-component"
            />
            <label for="name-input">{{
              'EVENT2_SEARCH.NAME' | translate
            }}</label>
          </span>
        </div>
        ....
----
// TODO: Explain the different possible input fields, explain the meaning of the directive: *ocxAdvanced 

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: Adapt the permission correctly to your project needs
Adapt the name of the permission accordingly to your defined permission in permission.csv file.
*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: Please specify the fields and the their content. + Please add here more search configs if needed
*Where this snippet can be found*: <feature>-search.component.html. :
[subs=+macros]
----
   searchConfigsEntries: SearchConfig[] = [
    {
      id: '01',
      name: 'Basic search config',
      version: 1,
      readonly: true,
      isAdvanced: false,
      values: {
        name: 'test',
    // ACTION: Please specify the fields and the their content.
      },
    },
    // ACTION: Please add here more search configs if needed, link to documentation: TODO
  ];
        ....
----
In the first ACTION, you can specify the fields which should be filled and you can specify the content (e.g. : 'test').

In the second ACTION, you can add more search configs which you can later select in the dropdown.
In the following a short explanation of the properties of the SearchConfig:

* id: id of the search config
* name: name of the search config
* version: current version of the search config (is later important for the migration of search configs)
* readonly: This property indicates if the search config can be overwritten. (This functionality will be implemnted in the future)
* isAdvanced: This property indicates if the search config belongs to advanced or basic search fields. If this property is set to true, the search config covers input fields from the advanced search.
* values: { ...} Here you can provide key-value pairs to specify which fields should be filled with with content.

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: Please select the column to be displayed
*Where this snippet can be found*: <feature>-search.component.html. :
[subs=+macros]
----
    // ACTION: Please select the column to be displayed
     // columnId = 'id';
    // column = this.columns.find((e) => e.id === this.columnId);
        ....
----
Please comment in the two lines of code and specify the columnId which results should be displayed in the visual diagram component. The diagram component shows the distribution of data of the selected column.

IN PROGRESS

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: Please add here the definition of your criteriaGroup, link to the documentation: 

IN PROGRESS

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: Add here the properties from the DTO which you want to map, documentation link:

IN PROGRESS

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: Add here the properties which you want you have displayed in your csv file in the header and map them

IN PROGRESS

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: Please define the members for your <%= featurePropertyName %>SearchCriteriasSchema here

IN PROGRESS

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: Here you can create a mapping of the items and their corresponding translation strings

IN PROGRESS

*HINT*: Please remove the "ACTION" comment after solving this issue

== Actions for details:

=== ACTION: add additional properties here

Where this snippet can be found: <feature>-bff.yaml. :

----
components:
  schemas:
    <Feature>Details:
      type: object
      properties:
        id:
          type: integer
          format: int64
        # ACTION: add additional properties here
----

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: ADD TRANSLATION

IN PROGRESS

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: add header values here

IN PROGRESS

*HINT*: Please remove the "ACTION" comment after solving this issue

=== ACTION: add sub-viewmodel interface for each tab in details and add it here

IN PROGRESS

*HINT*: Please remove the "ACTION" comment after solving this issue